# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class ApiVersion(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ApiVersion - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'looker_release_version': 'str',
            'current_version': 'ApiVersionElement',
            'supported_versions': 'list[ApiVersionElement]',
            'can': 'dict(str, bool)'
        }

        self.attribute_map = {
            'looker_release_version': 'looker_release_version',
            'current_version': 'current_version',
            'supported_versions': 'supported_versions',
            'can': 'can'
        }

        self._looker_release_version = None
        self._current_version = None
        self._supported_versions = None
        self._can = None

    @property
    def looker_release_version(self):
        """
        Gets the looker_release_version of this ApiVersion.
        Current Looker release version number

        :return: The looker_release_version of this ApiVersion.
        :rtype: str
        """
        return self._looker_release_version

    @looker_release_version.setter
    def looker_release_version(self, looker_release_version):
        """
        Sets the looker_release_version of this ApiVersion.
        Current Looker release version number

        :param looker_release_version: The looker_release_version of this ApiVersion.
        :type: str
        """
        self._looker_release_version = looker_release_version

    @property
    def current_version(self):
        """
        Gets the current_version of this ApiVersion.
        Current version for this Looker instance

        :return: The current_version of this ApiVersion.
        :rtype: ApiVersionElement
        """
        return self._current_version

    @current_version.setter
    def current_version(self, current_version):
        """
        Sets the current_version of this ApiVersion.
        Current version for this Looker instance

        :param current_version: The current_version of this ApiVersion.
        :type: ApiVersionElement
        """
        self._current_version = current_version

    @property
    def supported_versions(self):
        """
        Gets the supported_versions of this ApiVersion.
        Array of versions supported by this Looker instance

        :return: The supported_versions of this ApiVersion.
        :rtype: list[ApiVersionElement]
        """
        return self._supported_versions

    @supported_versions.setter
    def supported_versions(self, supported_versions):
        """
        Sets the supported_versions of this ApiVersion.
        Array of versions supported by this Looker instance

        :param supported_versions: The supported_versions of this ApiVersion.
        :type: list[ApiVersionElement]
        """
        self._supported_versions = supported_versions

    @property
    def can(self):
        """
        Gets the can of this ApiVersion.
        Operations the current user is able to perform on this object

        :return: The can of this ApiVersion.
        :rtype: dict(str, bool)
        """
        return self._can

    @can.setter
    def can(self, can):
        """
        Sets the can of this ApiVersion.
        Operations the current user is able to perform on this object

        :param can: The can of this ApiVersion.
        :type: dict(str, bool)
        """
        self._can = can

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

