# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class ContentMetaGroupUser(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ContentMetaGroupUser - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'content_metadata_id': 'str',
            'permission_type': 'str',
            'group_id': 'int',
            'user_id': 'int',
            'can': 'dict(str, bool)'
        }

        self.attribute_map = {
            'id': 'id',
            'content_metadata_id': 'content_metadata_id',
            'permission_type': 'permission_type',
            'group_id': 'group_id',
            'user_id': 'user_id',
            'can': 'can'
        }

        self._id = None
        self._content_metadata_id = None
        self._permission_type = None
        self._group_id = None
        self._user_id = None
        self._can = None

    @property
    def id(self):
        """
        Gets the id of this ContentMetaGroupUser.
        Unique Id

        :return: The id of this ContentMetaGroupUser.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ContentMetaGroupUser.
        Unique Id

        :param id: The id of this ContentMetaGroupUser.
        :type: str
        """
        self._id = id

    @property
    def content_metadata_id(self):
        """
        Gets the content_metadata_id of this ContentMetaGroupUser.
        Id of associated Content Metadata

        :return: The content_metadata_id of this ContentMetaGroupUser.
        :rtype: str
        """
        return self._content_metadata_id

    @content_metadata_id.setter
    def content_metadata_id(self, content_metadata_id):
        """
        Sets the content_metadata_id of this ContentMetaGroupUser.
        Id of associated Content Metadata

        :param content_metadata_id: The content_metadata_id of this ContentMetaGroupUser.
        :type: str
        """
        self._content_metadata_id = content_metadata_id

    @property
    def permission_type(self):
        """
        Gets the permission_type of this ContentMetaGroupUser.
        Type of permission: \"view\" or \"edit\"

        :return: The permission_type of this ContentMetaGroupUser.
        :rtype: str
        """
        return self._permission_type

    @permission_type.setter
    def permission_type(self, permission_type):
        """
        Sets the permission_type of this ContentMetaGroupUser.
        Type of permission: \"view\" or \"edit\"

        :param permission_type: The permission_type of this ContentMetaGroupUser.
        :type: str
        """
        self._permission_type = permission_type

    @property
    def group_id(self):
        """
        Gets the group_id of this ContentMetaGroupUser.
        ID of associated group

        :return: The group_id of this ContentMetaGroupUser.
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """
        Sets the group_id of this ContentMetaGroupUser.
        ID of associated group

        :param group_id: The group_id of this ContentMetaGroupUser.
        :type: int
        """
        self._group_id = group_id

    @property
    def user_id(self):
        """
        Gets the user_id of this ContentMetaGroupUser.
        ID of associated user

        :return: The user_id of this ContentMetaGroupUser.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this ContentMetaGroupUser.
        ID of associated user

        :param user_id: The user_id of this ContentMetaGroupUser.
        :type: int
        """
        self._user_id = user_id

    @property
    def can(self):
        """
        Gets the can of this ContentMetaGroupUser.
        Operations the current user is able to perform on this object

        :return: The can of this ContentMetaGroupUser.
        :rtype: dict(str, bool)
        """
        return self._can

    @can.setter
    def can(self, can):
        """
        Sets the can of this ContentMetaGroupUser.
        Operations the current user is able to perform on this object

        :param can: The can of this ContentMetaGroupUser.
        :type: dict(str, bool)
        """
        self._can = can

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

