# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class LookmlModelExploreFieldSqlCase(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        LookmlModelExploreFieldSqlCase - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'value': 'str',
            'condition': 'str',
            'can': 'dict(str, bool)'
        }

        self.attribute_map = {
            'value': 'value',
            'condition': 'condition',
            'can': 'can'
        }

        self._value = None
        self._condition = None
        self._can = None

    @property
    def value(self):
        """
        Gets the value of this LookmlModelExploreFieldSqlCase.
        SQL Case label value

        :return: The value of this LookmlModelExploreFieldSqlCase.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this LookmlModelExploreFieldSqlCase.
        SQL Case label value

        :param value: The value of this LookmlModelExploreFieldSqlCase.
        :type: str
        """
        self._value = value

    @property
    def condition(self):
        """
        Gets the condition of this LookmlModelExploreFieldSqlCase.
        SQL Case condition expression

        :return: The condition of this LookmlModelExploreFieldSqlCase.
        :rtype: str
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """
        Sets the condition of this LookmlModelExploreFieldSqlCase.
        SQL Case condition expression

        :param condition: The condition of this LookmlModelExploreFieldSqlCase.
        :type: str
        """
        self._condition = condition

    @property
    def can(self):
        """
        Gets the can of this LookmlModelExploreFieldSqlCase.
        Operations the current user is able to perform on this object

        :return: The can of this LookmlModelExploreFieldSqlCase.
        :rtype: dict(str, bool)
        """
        return self._can

    @can.setter
    def can(self, can):
        """
        Sets the can of this LookmlModelExploreFieldSqlCase.
        Operations the current user is able to perform on this object

        :param can: The can of this LookmlModelExploreFieldSqlCase.
        :type: dict(str, bool)
        """
        self._can = can

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

